export const externalItems = [
  {title: "12 Gauge Buckshot", shortname: "ammo.shotgun"},
  {title: "12 Gauge Incendiary Shell", shortname: "ammo.shotgun.fire"},
  {title: "12 Gauge Slug", shortname: "ammo.shotgun.slug"},
  {title: "16x Zoom Scope", shortname: "weapon.mod.8x.scope"},
  {title: "40mm HE Grenade", shortname: "ammo.grenadelauncher.he"},
  {title: "40mm Shotgun Round", shortname: "ammo.grenadelauncher.buckshot"},
  {title: "40mm Smoke Grenade", shortname: "ammo.grenadelauncher.smoke"},
  {title: "5.56 Rifle Ammo", shortname: "ammo.rifle"},
  {title: "8x Zoom Scope", shortname: "weapon.mod.small.scope"},
  {title: "A Barrel Costume", shortname: "barrelcostume"},
  {title: "Above Ground Pool", shortname: "abovegroundpool"},
  {title: "Acoustic Guitar", shortname: "fun.guitar"},
  {title: "Adv. Anti-Rad Tea", shortname: "radiationresisttea.advanced"},
  {title: "Advanced Healing Tea", shortname: "healingtea.advanced"},
  {title: "Advanced Max Health Tea", shortname: "maxhealthtea.advanced"},
  {title: "Advanced Ore Tea", shortname: "oretea.advanced"},
  {title: "Advanced Rad. Removal Tea", shortname: "radiationremovetea.advanced"},
  {title: "Advanced Scrap Tea", shortname: "scraptea.advanced"},
  {title: "Advanced Wood Tea", shortname: "woodtea.advanced"},
  {title: "Advent Calendar", shortname: "xmas.advent"},
  {title: "Anchovy", shortname: "fish.anchovy"},
  {title: "AND Switch", shortname: "electric.andswitch"},
  {title: "Animal Fat", shortname: "fat.animal"},
  {title: "Anti-Rad Tea", shortname: "radiationresisttea"},
  {title: "Anti-Radiation Pills", shortname: "antiradpills"},
  {title: "Apple", shortname: "apple"},
  {title: "Arctic Scientist Suit", shortname: "hazmatsuit_scientist_arctic"},
  {title: "Arctic Suit", shortname: "hazmatsuit.arcticsuit"},
  {title: "Armored Cockpit Vehicle Module", shortname: "vehicle.1mod.cockpit.armored"},
  {title: "Armored Door", shortname: "door.hinged.toptier"},
  {title: "Armored Double Door", shortname: "door.double.hinged.toptier"},
  {title: "Armored Passenger Vehicle Module", shortname: "vehicle.1mod.passengers.armored"},
  {title: "Assault Rifle", shortname: "rifle.ak"},
  {title: "Assault Rifle - ICE", shortname: "rifle.ak.ice"},
  {title: "Audio Alarm", shortname: "electric.audioalarm"},
  {title: "Auto Turret", shortname: "autoturret"},
  {title: "Bandage", shortname: "bandage"},
  {title: "Bandana Mask", shortname: "mask.bandana"},
  {title: "Bandit Guard Gear", shortname: "attire.banditguard"},
  {title: "Barbed Wooden Barricade", shortname: "barricade.woodwire"},
  {title: "Barbeque", shortname: "bbq"},
  {title: "Baseball Bat", shortname: "mace.baseballbat"},
  {title: "Baseball Cap", shortname: "hat.cap"},
  {title: "Basic Healing Tea", shortname: "healingtea"},
  {title: "Basic Horse Shoes", shortname: "horse.shoes.basic"},
  {title: "Basic Max Health Tea", shortname: "maxhealthtea"},
  {title: "Basic Ore Tea", shortname: "oretea"},
  {title: "Basic Scrap Tea", shortname: "scraptea"},
  {title: "Basic Wood Tea", shortname: "woodtea"},
  {title: "Battery - Small", shortname: "battery.small"},
  {title: "Beach Chair", shortname: "beachchair"},
  {title: "Beach Parasol", shortname: "beachparasol"},
  {title: "Beach Table", shortname: "beachtable"},
  {title: "Beach Towel", shortname: "beachtowel"},
  {title: "Beancan Grenade", shortname: "grenade.beancan"},
  {title: "Bed", shortname: "bed"},
  {title: "Beenie Hat", shortname: "hat.beenie"},
  {title: "Binoculars", shortname: "tool.binoculars"},
  {title: "Birthday Cake", shortname: "cakefiveyear"},
  {title: "Black Berry", shortname: "black.berry"},
  {title: "Black Berry Clone", shortname: "clone.black.berry"},
  {title: "Black Berry Seed", shortname: "seed.black.berry"},
  {title: "Black Raspberries", shortname: "black.raspberries"},
  {title: "Bleach", shortname: "bleach"},
  {title: "Blocker", shortname: "electric.blocker"},
  {title: "Blood", shortname: "blood"},
  {title: "Blue Berry", shortname: "blue.berry"},
  {title: "Blue Berry Clone", shortname: "clone.blue.berry"},
  {title: "Blue Berry Seed", shortname: "seed.blue.berry"},
  {title: "Blue Boomer", shortname: "firework.boomer.blue"},
  {title: "Blue Dog Tags", shortname: "bluedogtags"},
  {title: "Blue Jumpsuit", shortname: "jumpsuit.suit.blue"},
  {title: "Blue Keycard", shortname: "keycard_blue"},
  {title: "Blue Roman Candle", shortname: "firework.romancandle.blue"},
  {title: "Blueberries", shortname: "blueberries"},
  {title: "Blueprint", shortname: "blueprintbase"},
  {title: "Bolt Action Rifle", shortname: "rifle.bolt"},
  {title: "Bone Armor", shortname: "bone.armor.suit"},
  {title: "Bone Arrow", shortname: "arrow.bone"},
  {title: "Bone Club", shortname: "bone.club"},
  {title: "Bone Fragments", shortname: "bone.fragments"},
  {title: "Bone Helmet", shortname: "deer.skull.mask"},
  {title: "Bone Knife", shortname: "knife.bone"},
  {title: "Boogie Board", shortname: "boogieboard"},
  {title: "Boom Box", shortname: "boombox"},
  {title: "Boonie Hat", shortname: "hat.boonie"},
  {title: "Boots", shortname: "shoes.boots"},
  {title: "Bota Bag", shortname: "botabag"},
  {title: "Bronze Egg", shortname: "easter.bronzeegg"},
  {title: "Bucket Helmet", shortname: "bucket.helmet"},
  {title: "Building Plan", shortname: "building.planner"},
  {title: "Bunny Ears", shortname: "attire.bunnyears"},
  {title: "Bunny Hat", shortname: "hat.bunnyhat"},
  {title: "Bunny Onesie", shortname: "attire.bunny.onesie"},
  {title: "Burlap Gloves", shortname: "burlap.gloves.new"},
  {title: "Burlap Headwrap", shortname: "burlap.headwrap"},
  {title: "Burlap Shirt", shortname: "burlap.shirt"},
  {title: "Burlap Shoes", shortname: "burlap.shoes"},
  {title: "Burlap Trousers", shortname: "burlap.trousers"},
  {title: "Burnt Bear Meat", shortname: "bearmeat.burned"},
  {title: "Burnt Chicken", shortname: "chicken.burned"},
  {title: "Burnt Deer Meat", shortname: "deermeat.burned"},
  {title: "Burnt Horse Meat", shortname: "horsemeat.burned"},
  {title: "Burnt Human Meat", shortname: "humanmeat.burned"},
  {title: "Burnt Pork", shortname: "meat.pork.burned"},
  {title: "Burnt Wolf Meat", shortname: "wolfmeat.burned"},
  {title: "Burst Module", shortname: "weapon.mod.burstmodule"},
  {title: "Butcher Knife", shortname: "knife.butcher"},
  {title: "Button", shortname: "electric.button"},
  {title: "Cable Tunnel", shortname: "electric.cabletunnel"},
  {title: "Cactus Flesh", shortname: "cactusflesh"},
  {title: "Camera", shortname: "tool.camera"},
  {title: "Camp Fire", shortname: "campfire"},
  {title: "Camper Vehicle Module", shortname: "vehicle.2mod.camper"},
  {title: "Can of Beans", shortname: "can.beans"},
  {title: "Can of Tuna", shortname: "can.tuna"},
  {title: "Canbourine", shortname: "fun.tambourine"},
  {title: "Candle Hat", shortname: "hat.candle"},
  {title: "Candy Cane", shortname: "candycane"},
  {title: "Candy Cane Club", shortname: "candycaneclub"},
  {title: "Captain's Log", shortname: "captainslog"},
  {title: "Car Key", shortname: "car.key"},
  {title: "Card Movember Moustache", shortname: "movembermoustachecard"},
  {title: "Card Table", shortname: "cardtable"},
  {title: "Carvable Pumpkin", shortname: "carvable.pumpkin"},
  {title: "Cassette - Long", shortname: "cassette"},
  {title: "Cassette - Medium", shortname: "cassette.medium"},
  {title: "Cassette - Short", shortname: "cassette.short"},
  {title: "Cassette Recorder", shortname: "fun.casetterecorder"},
  {title: "Catfish", shortname: "fish.catfish"},
  {title: "CCTV Camera", shortname: "cctv.camera"},
  {title: "Ceiling Light", shortname: "ceilinglight"},
  {title: "Chainlink Fence", shortname: "wall.frame.fence"},
  {title: "Chainlink Fence Gate", shortname: "wall.frame.fence.gate"},
  {title: "Chainsaw", shortname: "chainsaw"},
  {title: "Chair", shortname: "chair"},
  {title: "Champagne Boomer", shortname: "firework.boomer.champagne"},
  {title: "Charcoal", shortname: "charcoal"},
  {title: "Chinese Lantern", shortname: "chineselantern"},
  {title: "Chippy Arcade Game", shortname: "arcade.machine.chippy"},
  {title: "Chocolate Bar", shortname: "chocolate"},
  {title: "Christmas Door Wreath", shortname: "xmasdoorwreath"},
  {title: "Christmas Lights", shortname: "xmas.lightstring"},
  {title: "Christmas Tree", shortname: "xmas.tree"},
  {title: "Clatter Helmet", shortname: "clatter.helmet"},
  {title: "Cloth", shortname: "cloth"},
  {title: "Coal 🙁", shortname: "coal"},
  {title: "Cockpit Vehicle Module", shortname: "vehicle.1mod.cockpit"},
  {title: "Cockpit With Engine Vehicle Module", shortname: "vehicle.1mod.cockpit.with.engine"},
  {title: "Code Lock", shortname: "lock.code"},
  {title: "Coffee Can Helmet", shortname: "coffeecan.helmet"},
  {title: "Coffin", shortname: "coffin.storage"},
  {title: "Combat Knife", shortname: "knife.combat"},
  {title: "Composter", shortname: "composter"},
  {title: "Compound Bow", shortname: "bow.compound"},
  {title: "Computer Station", shortname: "computerstation"},
  {title: "Concrete Barricade", shortname: "barricade.concrete"},
  {title: "Concrete Hatchet", shortname: "concretehatchet"},
  {title: "Concrete Pickaxe", shortname: "concretepickaxe"},
  {title: "Connected Speaker", shortname: "connected.speaker"},
  {title: "Cooked Bear Meat", shortname: "bearmeat.cooked"},
  {title: "Cooked Chicken", shortname: "chicken.cooked"},
  {title: "Cooked Deer Meat", shortname: "deermeat.cooked"},
  {title: "Cooked Fish", shortname: "fish.cooked"},
  {title: "Cooked Horse Meat", shortname: "horsemeat.cooked"},
  {title: "Cooked Human Meat", shortname: "humanmeat.cooked"},
  {title: "Cooked Pork", shortname: "meat.pork.cooked"},
  {title: "Cooked Wolf Meat", shortname: "wolfmeat.cooked"},
  {title: "Corn", shortname: "corn"},
  {title: "Corn Clone", shortname: "clone.corn"},
  {title: "Corn Seed", shortname: "seed.corn"},
  {title: "Counter", shortname: "electric.counter"},
  {title: "Cowbell", shortname: "fun.cowbell"},
  {title: "Crate Costume", shortname: "cratecostume"},
  {title: "Crossbow", shortname: "crossbow"},
  {title: "Crude Oil", shortname: "crude.oil"},
  {title: "Cultist Deer Torch", shortname: "torch.torch.skull"},
  {title: "Cursed Cauldron", shortname: "cursedcauldron"},
  {title: "Custom SMG", shortname: "smg.2"},
  {title: "Decorative Baubels", shortname: "xmas.decoration.baubels"},
  {title: "Decorative Gingerbread Men", shortname: "xmas.decoration.gingerbreadmen"},
  {title: "Decorative Pinecones", shortname: "xmas.decoration.pinecone"},
  {title: "Decorative Plastic Candy Canes", shortname: "xmas.decoration.candycanes"},
  {title: "Decorative Tinsel", shortname: "xmas.decoration.tinsel"},
  {title: "Deluxe Christmas Lights", shortname: "xmas.lightstring.advanced"},
  {title: "Diesel Fuel", shortname: "diesel_barrel"},
  {title: "Disco Ball", shortname: "discoball"},
  {title: "Disco Floor", shortname: "discofloor.largetiles"},
  {title: "Disco Floor", shortname: "discofloor"},
  {title: "Diving Fins", shortname: "diving.fins"},
  {title: "Diving Mask", shortname: "diving.mask"},
  {title: "Diving Tank", shortname: "diving.tank"},
  {title: "Dog Tag", shortname: "dogtagneutral"},
  {title: "Door Closer", shortname: "door.closer"},
  {title: "Door Controller", shortname: "electric.doorcontroller"},
  {title: "Door Key", shortname: "door.key"},
  {title: "Double Barrel Shotgun", shortname: "shotgun.double"},
  {title: "Double Sign Post", shortname: "sign.post.double"},
  {title: "Dragon Door Knocker", shortname: "dragondoorknocker"},
  {title: "Dragon Mask", shortname: "hat.dragonmask"},
  {title: "Drone", shortname: "drone"},
  {title: "Drop Box", shortname: "dropbox"},
  {title: "Duct Tape", shortname: "ducttape"},
  {title: "Duo Submarine", shortname: "submarineduo"},
  {title: "Easter Door Wreath", shortname: "easterdoorwreath"},
  {title: "Egg Basket", shortname: "easterbasket"},
  {title: "Egg Suit", shortname: "attire.egg.suit"},
  {title: "Egg Suit Sign Test", shortname: "sign.egg.suit"},
  {title: "Electric Furnace", shortname: "electric.furnace"},
  {title: "Electric Fuse", shortname: "fuse"},
  {title: "Electric Heater", shortname: "electric.heater"},
  {title: "Electrical Branch", shortname: "electrical.branch"},
  {title: "Elevator", shortname: "elevator"},
  {title: "Empty Can Of Beans", shortname: "can.beans.empty"},
  {title: "Empty Propane Tank", shortname: "propanetank"},
  {title: "Empty Tuna Can", shortname: "can.tuna.empty"},
  {title: "Engine Vehicle Module", shortname: "vehicle.1mod.engine"},
  {title: "Eoka Pistol", shortname: "pistol.eoka"},
  {title: "Explosive 5.56 Rifle Ammo", shortname: "ammo.rifle.explosive"},
  {title: "Explosives", shortname: "explosives"},
  {title: "Extended Magazine", shortname: "weapon.mod.extendedmags"},
  {title: "F1 Grenade", shortname: "grenade.f1"},
  {title: "Factory Door", shortname: "factorydoor"},
  {title: "Fertilizer", shortname: "fertilizer"},
  {title: "Festive Doorway Garland", shortname: "xmas.door.garland"},
  {title: "Festive Double Doorway Garland", shortname: "xmas.double.door.garland"},
  {title: "Festive Window Garland", shortname: "xmas.window.garland"},
  {title: "Fire Arrow", shortname: "arrow.fire"},
  {title: "Firecracker String", shortname: "lunar.firecrackers"},
  {title: "Fishing Tackle", shortname: "fishing.tackle"},
  {title: "Flame Thrower", shortname: "flamethrower"},
  {title: "Flame Turret", shortname: "flameturret"},
  {title: "Flare", shortname: "flare"},
  {title: "Flashbang", shortname: "grenade.flashbang"},
  {title: "Flasher Light", shortname: "electric.flasherlight"},
  {title: "Flashlight", shortname: "flashlight.held"},
  {title: "Flatbed Vehicle Module", shortname: "vehicle.1mod.flatbed"},
  {title: "Floor grill", shortname: "floor.grill"},
  {title: "Floor triangle grill", shortname: "floor.triangle.grill"},
  {title: "Fluid Combiner", shortname: "fluid.combiner"},
  {title: "Fluid Splitter", shortname: "fluid.splitter"},
  {title: "Fluid Switch &amp; Pump", shortname: "fluid.switch"},
  {title: "Fogger-3000", shortname: "fogmachine"},
  {title: "Frankenstein Table", shortname: "frankensteintable"},
  {title: "Fridge", shortname: "fridge"},
  {title: "Frog Boots", shortname: "boots.frog"},
  {title: "Fuel Tank Vehicle Module", shortname: "vehicle.2mod.fuel.tank"},
  {title: "Furnace", shortname: "furnace"},
  {title: "Garage Door", shortname: "wall.frame.garagedoor"},
  {title: "Garry's Mod Tool Gun", shortname: "toolgun"},
  {title: "Gas Mask", shortname: "hat.gas.mask"},
  {title: "Gears", shortname: "gears"},
  {title: "Geiger Counter", shortname: "geiger.counter"},
  {title: "Ghost Costume", shortname: "ghostsheet"},
  {title: "Giant Candy Decor", shortname: "giantcandycanedecor"},
  {title: "Giant Lollipop Decor", shortname: "giantlollipops"},
  {title: "Gingerbread Suit", shortname: "gingerbreadsuit"},
  {title: "Glowing Eyes", shortname: "gloweyes"},
  {title: "Glue", shortname: "glue"},
  {title: "Gold Egg", shortname: "easter.goldegg"},
  {title: "Granola Bar", shortname: "granolabar"},
  {title: "Gravestone", shortname: "gravestone"},
  {title: "Graveyard Fence", shortname: "wall.graveyard.fence"},
  {title: "Green Berry", shortname: "green.berry"},
  {title: "Green Berry Clone", shortname: "clone.green.berry"},
  {title: "Green Berry Seed", shortname: "seed.green.berry"},
  {title: "Green Boomer", shortname: "firework.boomer.green"},
  {title: "Green Industrial Wall Light", shortname: "industrial.wall.light.green"},
  {title: "Green Keycard", shortname: "keycard_green"},
  {title: "Green Roman Candle", shortname: "firework.romancandle.green"},
  {title: "Grub", shortname: "grub"},
  {title: "Gun Powder", shortname: "gunpowder"},
  {title: "Hab Repair", shortname: "habrepair"},
  {title: "Halloween Candy", shortname: "halloween.candy"},
  {title: "Hammer", shortname: "hammer"},
  {title: "Handmade Fishing Rod", shortname: "fishingrod.handmade"},
  {title: "Handmade Shell", shortname: "ammo.handmade.shell"},
  {title: "Hatchet", shortname: "hatchet"},
  {title: "Hazmat Suit", shortname: "hazmatsuit"},
  {title: "HBHF Sensor", shortname: "electric.hbhfsensor"},
  {title: "Headset", shortname: "twitch.headset"},
  {title: "Heavy Frankenstein Head", shortname: "frankensteins.monster.03.head"},
  {title: "Heavy Frankenstein Legs", shortname: "frankensteins.monster.03.legs"},
  {title: "Heavy Frankenstein Torso", shortname: "frankensteins.monster.03.torso"},
  {title: "Heavy Plate Helmet", shortname: "heavy.plate.helmet"},
  {title: "Heavy Plate Jacket", shortname: "heavy.plate.jacket"},
  {title: "Heavy Plate Pants", shortname: "heavy.plate.pants"},
  {title: "Heavy Scientist Suit", shortname: "scientistsuit_heavy"},
  {title: "Hemp Clone", shortname: "clone.hemp"},
  {title: "Hemp Seed", shortname: "seed.hemp"},
  {title: "Herring", shortname: "fish.herring"},
  {title: "Hide Boots", shortname: "attire.hide.boots"},
  {title: "Hide Halterneck", shortname: "attire.hide.helterneck"},
  {title: "Hide Pants", shortname: "attire.hide.pants"},
  {title: "Hide Poncho", shortname: "attire.hide.poncho"},
  {title: "Hide Skirt", shortname: "attire.hide.skirt"},
  {title: "Hide Vest", shortname: "attire.hide.vest"},
  {title: "High External Stone Gate", shortname: "gates.external.high.stone"},
  {title: "High External Stone Wall", shortname: "wall.external.high.stone"},
  {title: "High External Wooden Gate", shortname: "gates.external.high.wood"},
  {title: "High External Wooden Wall", shortname: "wall.external.high"},
  {title: "High Ice Wall", shortname: "wall.external.high.ice"},
  {title: "High Quality Carburetor", shortname: "carburetor3"},
  {title: "High Quality Crankshaft", shortname: "crankshaft3"},
  {title: "High Quality Horse Shoes", shortname: "horse.shoes.advanced"},
  {title: "High Quality Metal", shortname: "metal.refined"},
  {title: "High Quality Metal Ore", shortname: "hq.metal.ore"},
  {title: "High Quality Pistons", shortname: "piston3"},
  {title: "High Quality Spark Plugs", shortname: "sparkplug3"},
  {title: "High Quality Valves", shortname: "valve3"},
  {title: "High Velocity Arrow", shortname: "arrow.hv"},
  {title: "High Velocity Rocket", shortname: "ammo.rocket.hv"},
  {title: "Hitch &amp; Trough", shortname: "hitchtroughcombo"},
  {title: "HMLMG", shortname: "hmlmg"},
  {title: "Hobo Barrel", shortname: "hobobarrel"},
  {title: "Hockey Mask", shortname: "metal.facemask.hockey"},
  {title: "Holosight", shortname: "weapon.mod.holosight"},
  {title: "Homemade Landmine", shortname: "trap.landmine"},
  {title: "Hoodie", shortname: "hoodie"},
  {title: "Horse Dung", shortname: "horsedung"},
  {title: "Horse Saddle", shortname: "horse.saddle"},
  {title: "Hose Tool", shortname: "hosetool"},
  {title: "Huge Wooden Sign", shortname: "sign.wooden.huge"},
  {title: "Human Skull", shortname: "skull.human"},
  {title: "Hunting Bow", shortname: "bow.hunting"},
  {title: "HV 5.56 Rifle Ammo", shortname: "ammo.rifle.hv"},
  {title: "HV Pistol Ammo", shortname: "ammo.pistol.hv"},
  {title: "Ice Metal Chest Plate", shortname: "metal.plate.torso.icevest"},
  {title: "Ice Metal Facemask", shortname: "metal.facemask.icemask"},
  {title: "Ice Throne", shortname: "chair.icethrone"},
  {title: "Igniter", shortname: "electric.igniter"},
  {title: "Improvised Balaclava", shortname: "mask.balaclava"},
  {title: "Incendiary 5.56 Rifle Ammo", shortname: "ammo.rifle.incendiary"},
  {title: "Incendiary Pistol Bullet", shortname: "ammo.pistol.fire"},
  {title: "Incendiary Rocket", shortname: "ammo.rocket.fire"},
  {title: "Industrial Combiner", shortname: "industrial.combiner"},
  {title: "Industrial Conveyor", shortname: "industrial.conveyor"},
  {title: "Industrial Crafter", shortname: "industrial.crafter"},
  {title: "Industrial Door", shortname: "door.hinged.industrial.a"},
  {title: "Industrial Splitter", shortname: "industrial.splitter"},
  {title: "Industrial Wall Light", shortname: "industrial.wall.light"},
  {title: "Inner Tube", shortname: "innertube"},
  {title: "Inner Tube", shortname: "innertube.horse"},
  {title: "Inner Tube", shortname: "innertube.unicorn"},
  {title: "Instant Camera", shortname: "tool.instant_camera"},
  {title: "Jack O Lantern Angry", shortname: "jackolantern.angry"},
  {title: "Jack O Lantern Happy", shortname: "jackolantern.happy"},
  {title: "Jacket", shortname: "jacket"},
  {title: "Jackhammer", shortname: "jackhammer"},
  {title: "Jerry Can Guitar", shortname: "fun.jerrycanguitar"},
  {title: "Jumpsuit", shortname: "jumpsuit.suit"},
  {title: "Junkyard Drum Kit", shortname: "drumkit"},
  {title: "Kayak", shortname: "kayak"},
  {title: "Key Lock", shortname: "lock.key"},
  {title: "L96 Rifle", shortname: "rifle.l96"},
  {title: "Ladder Hatch", shortname: "floor.ladder.hatch"},
  {title: "Landscape Photo Frame", shortname: "photoframe.landscape"},
  {title: "Landscape Picture Frame", shortname: "sign.pictureframe.landscape"},
  {title: "Lantern", shortname: "lantern"},
  {title: "Large Animated Neon Sign", shortname: "sign.neon.xl.animated"},
  {title: "Large Banner Hanging", shortname: "sign.hanging.banner.large"},
  {title: "Large Banner on pole", shortname: "sign.pole.banner.large"},
  {title: "Large Candle Set", shortname: "largecandles"},
  {title: "Large Chassis", shortname: "vehicle.chassis.4mod"},
  {title: "Large Flatbed Vehicle Module", shortname: "vehicle.2mod.flatbed"},
  {title: "Large Furnace", shortname: "furnace.large"},
  {title: "Large Loot Bag", shortname: "halloween.lootbag.large"},
  {title: "Large Medkit", shortname: "largemedkit"},
  {title: "Large Neon Sign", shortname: "sign.neon.xl"},
  {title: "Large Photo Frame", shortname: "photoframe.large"},
  {title: "Large Planter Box", shortname: "planter.large"},
  {title: "Large Present", shortname: "xmas.present.large"},
  {title: "Large Rechargeable Battery", shortname: "electric.battery.rechargable.large"},
  {title: "Large Solar Panel", shortname: "electric.solarpanel.large"},
  {title: "Large Water Catcher", shortname: "water.catcher.large"},
  {title: "Large Wood Box", shortname: "box.wooden.large"},
  {title: "Large Wooden Sign", shortname: "sign.wooden.large"},
  {title: "Laser Detector", shortname: "electric.laserdetector"},
  {title: "Laser Light", shortname: "laserlight"},
  {title: "Leather", shortname: "leather"},
  {title: "Leather Gloves", shortname: "burlap.gloves"},
  {title: "Light Frankenstein Head", shortname: "frankensteins.monster.01.head"},
  {title: "Light Frankenstein Legs", shortname: "frankensteins.monster.01.legs"},
  {title: "Light Frankenstein Torso", shortname: "frankensteins.monster.01.torso"},
  {title: "Locker", shortname: "locker"},
  {title: "Locomotive", shortname: "locomotive"},
  {title: "Longsleeve T-Shirt", shortname: "tshirt.long"},
  {title: "Longsword", shortname: "longsword"},
  {title: "Low Grade Fuel", shortname: "lowgradefuel"},
  {title: "Low Quality Carburetor", shortname: "carburetor1"},
  {title: "Low Quality Crankshaft", shortname: "crankshaft1"},
  {title: "Low Quality Pistons", shortname: "piston1"},
  {title: "Low Quality Spark Plugs", shortname: "sparkplug1"},
  {title: "Low Quality Valves", shortname: "valve1"},
  {title: "LR-300 Assault Rifle", shortname: "rifle.lr300"},
  {title: "Lumberjack Hoodie", shortname: "lumberjack hoodie"},
  {title: "Lumberjack Suit", shortname: "hazmatsuit.lumberjack"},
  {title: "M249", shortname: "lmg.m249"},
  {title: "M39 Rifle", shortname: "rifle.m39"},
  {title: "M92 Pistol", shortname: "pistol.m92"},
  {title: "Mace", shortname: "mace"},
  {title: "Machete", shortname: "machete"},
  {title: "Mail Box", shortname: "mailbox"},
  {title: "MC repair", shortname: "minihelicopter.repair"},
  {title: "Medical Syringe", shortname: "syringe.medical"},
  {title: "Medium Animated Neon Sign", shortname: "sign.neon.125x215.animated"},
  {title: "Medium Chassis", shortname: "vehicle.chassis.3mod"},
  {title: "Medium Frankenstein Head", shortname: "frankensteins.monster.02.head"},
  {title: "Medium Frankenstein Legs", shortname: "frankensteins.monster.02.legs"},
  {title: "Medium Frankenstein Torso", shortname: "frankensteins.monster.02.torso"},
  {title: "Medium Loot Bag", shortname: "halloween.lootbag.medium"},
  {title: "Medium Neon Sign", shortname: "sign.neon.125x215"},
  {title: "Medium Present", shortname: "xmas.present.medium"},
  {title: "Medium Quality Carburetor", shortname: "carburetor2"},
  {title: "Medium Quality Crankshaft", shortname: "crankshaft2"},
  {title: "Medium Quality Pistons", shortname: "piston2"},
  {title: "Medium Quality Spark Plugs", shortname: "sparkplug2"},
  {title: "Medium Quality Valves", shortname: "valve2"},
  {title: "Medium Rechargeable Battery", shortname: "electric.battery.rechargable.medium"},
  {title: "Medium Wooden Sign", shortname: "sign.wooden.medium"},
  {title: "Megaphone", shortname: "megaphone"},
  {title: "Memory Cell", shortname: "electrical.memorycell"},
  {title: "Metal Barricade", shortname: "barricade.metal"},
  {title: "Metal Blade", shortname: "metalblade"},
  {title: "Metal Chest Plate", shortname: "metal.plate.torso"},
  {title: "Metal Facemask", shortname: "metal.facemask"},
  {title: "Metal Fragments", shortname: "metal.fragments"},
  {title: "Metal horizontal embrasure", shortname: "shutter.metal.embrasure.a"},
  {title: "Metal Ore", shortname: "metal.ore"},
  {title: "Metal Pipe", shortname: "metalpipe"},
  {title: "Metal Shop Front", shortname: "wall.frame.shopfront.metal"},
  {title: "Metal Spring", shortname: "metalspring"},
  {title: "Metal Vertical embrasure", shortname: "shutter.metal.embrasure.b"},
  {title: "Metal Window Bars", shortname: "wall.window.bars.metal"},
  {title: "Microphone Stand",shortname: "microphonestand"},
  {title: "Miners Hat", shortname: "hat.miner"},
  {title: "Mining Quarry", shortname: "mining.quarry"},
  {title: "Minnows", shortname: "fish.minnows"},
  {title: "Mixing Table", shortname: "mixingtable"},
  {title: "MLRS Aiming Module", shortname: "aiming.module.mlrs"},
  {title: "MLRS Rocket", shortname: "ammo.rocket.mlrs"},
  {title: "Mobile Phone", shortname: "mobilephone"},
  {title: "Modular Car Lift", shortname: "modularcarlift"},
  {title: "Molotov Cocktail", shortname: "grenade.molotov"},
  {title: "Movember Moustache", shortname: "movembermoustache"},
  {title: "MP5A4", shortname: "smg.mp5"},
  {title: "Multiple Grenade Launcher", shortname: "multiplegrenadelauncher"},
  {title: "Mummy Suit", shortname: "halloween.mummysuit"},
  {title: "Mushroom", shortname: "mushroom"},
  {title: "Muzzle Boost", shortname: "weapon.mod.muzzleboost"},
  {title: "Muzzle Brake", shortname: "weapon.mod.muzzlebrake"},
  {title: "Nailgun", shortname: "pistol.nailgun"},
  {title: "Nailgun Nails", shortname: "ammo.nailgun.nails"},
  {title: "Nest Hat", shortname: "attire.nesthat"},
  {title: "Netting", shortname: "wall.frame.netting"},
  {title: "New Year Gong", shortname: "newyeargong"},
  {title: "Night Vision Goggles", shortname: "nightvisiongoggles"},
  {title: "Ninja Suit", shortname: "attire.ninja.suit"},
  {title: "Nomad Suit", shortname: "hazmatsuit.nomadsuit"},
  {title: "Note", shortname: "note"},
  {title: "One Sided Town Sign Post", shortname: "sign.post.town"},
  {title: "OR Switch", shortname: "electric.orswitch"},
  {title: "Orange Boomer", shortname: "firework.boomer.orange"},
  {title: "Orange Roughy", shortname: "fish.orangeroughy"},
  {title: "Ox Mask", shortname: "hat.oxmask"},
  {title: "Paddle", shortname: "paddle"},
  {title: "Paddling Pool", shortname: "paddlingpool"},
  {title: "Painted Egg", shortname: "easter.paintedeggs"},
  {title: "Pan Flute", shortname: "fun.flute"},
  {title: "Pants", shortname: "pants"},
  {title: "Paper", shortname: "paper"},
  {title: "Paper Map", shortname: "map"},
  {title: "Party Hat", shortname: "partyhat"},
  {title: "Passenger Vehicle Module", shortname: "vehicle.2mod.passengers"},
  {title: "Pattern Boomer", shortname: "firework.boomer.pattern"},
  {title: "Photograph", shortname: "photo"},
  {title: "Pickaxe", shortname: "pickaxe"},
  {title: "Pickles", shortname: "jar.pickle"},
  {title: "Pipe Tool", shortname: "pipetool"},
  {title: "Pistol Bullet", shortname: "ammo.pistol"},
  {title: "Pitchfork", shortname: "pitchfork"},
  {title: "Plant Fiber", shortname: "plantfiber"},
  {title: "Plumber's Trumpet", shortname: "fun.trumpet"},
  {title: "Pookie Bear", shortname: "pookie.bear"},
  {title: "Portable Boom Box", shortname: "fun.boomboxportable"},
  {title: "Portrait Photo Frame", shortname: "photoframe.portrait"},
  {title: "Portrait Picture Frame", shortname: "sign.pictureframe.portrait"},
  {title: "Potato", shortname: "potato"},
  {title: "Potato Clone", shortname: "clone.potato"},
  {title: "Potato Seed", shortname: "seed.potato"},
  {title: "Powered Water Purifier", shortname: "powered.water.purifier"},
  {title: "Pressure Pad", shortname: "electric.pressurepad"},
  {title: "Prison Cell Gate", shortname: "wall.frame.cell.gate"},
  {title: "Prison Cell Wall", shortname: "wall.frame.cell"},
  {title: "Prototype 17", shortname: "pistol.prototype17"},
  {title: "Prototype Hatchet", shortname: "lumberjack.hatchet"},
  {title: "Prototype Pickaxe", shortname: "lumberjack.pickaxe"},
  {title: "Pump Jack", shortname: "mining.pumpjack"},
  {title: "Pump Shotgun", shortname: "shotgun.pump"},
  {title: "Pumpkin", shortname: "pumpkin"},
  {title: "Pumpkin Bucket", shortname: "pumpkinbasket"},
  {title: "Pumpkin Plant Clone", shortname: "clone.pumpkin"},
  {title: "Pumpkin Seed", shortname: "seed.pumpkin"},
  {title: "Pure Anti-Rad Tea", shortname: "radiationresisttea.pure"},
  {title: "Pure Healing Tea", shortname: "healingtea.pure"},
  {title: "Pure Max Health Tea", shortname: "maxhealthtea.pure"},
  {title: "Pure Ore Tea", shortname: "oretea.pure"},
  {title: "Pure Rad. Removal Tea", shortname: "radiationremovetea.pure"},
  {title: "Pure Scrap Tea", shortname: "scraptea.pure"},
  {title: "Pure Wood Tea", shortname: "woodtea.pure"},
  {title: "Purple Sunglasses", shortname: "twitchsunglasses"},
  {title: "Python Revolver", shortname: "pistol.python"},
  {title: "Rabbit Mask", shortname: "hat.rabbitmask"},
  {title: "Rad. Removal Tea", shortname: "radiationremovetea"},
  {title: "RAND Switch", shortname: "electric.random.switch"},
  {title: "Rat Mask", shortname: "hat.ratmask"},
  {title: "Raw Bear Meat", shortname: "bearmeat"},
  {title: "Raw Chicken Breast", shortname: "chicken.raw"},
  {title: "Raw Deer Meat", shortname: "deermeat.raw"},
  {title: "Raw Fish", shortname: "fish.raw"},
  {title: "Raw Horse Meat", shortname: "horsemeat.raw"},
  {title: "Raw Human Meat", shortname: "humanmeat.raw"},
  {title: "Raw Pork", shortname: "meat.boar"},
  {title: "Raw Wolf Meat", shortname: "wolfmeat.raw"},
  {title: "Reactive Target", shortname: "target.reactive"},
  {title: "Rear Seats Vehicle Module", shortname: "vehicle.1mod.rear.seats"},
  {title: "Red Berry", shortname: "red.berry"},
  {title: "Red Berry Clone", shortname: "clone.red.berry"},
  {title: "Red Berry Seed", shortname: "seed.red.berry"},
  {title: "Red Boomer", shortname: "firework.boomer.red"},
  {title: "Red Dog Tags", shortname: "reddogtags"},
  {title: "Red Industrial Wall Light", shortname: "industrial.wall.light.red"},
  {title: "Red Keycard", shortname: "keycard_red"},
  {title: "Red Roman Candle", shortname: "firework.romancandle.red"},
  {title: "Red Volcano Firework", shortname: "firework.volcano.red"},
  {title: "Reindeer Antlers", shortname: "attire.reindeer.headband"},
  {title: "Reinforced Glass Window", shortname: "wall.window.bars.toptier"},
  {title: "Repair Bench", shortname: "box.repair.bench"},
  {title: "Research Paper", shortname: "researchpaper"},
  {title: "Research Table", shortname: "research.table"},
  {title: "Revolver", shortname: "pistol.revolver"},
  {title: "RF Broadcaster", shortname: "electric.rf.broadcaster"},
  {title: "RF Pager", shortname: "rf_pager"},
  {title: "RF Receiver", shortname: "electric.rf.receiver"},
  {title: "RF Transmitter", shortname: "rf.detonator"},
  {title: "Rifle Body", shortname: "riflebody"},
  {title: "Riot Helmet", shortname: "riot.helmet"},
  {title: "Road Sign Jacket", shortname: "roadsign.jacket"},
  {title: "Road Sign Kilt", shortname: "roadsign.kilt"},
  {title: "Road Signs", shortname: "roadsigns"},
  {title: "Roadsign Gloves", shortname: "roadsign.gloves"},
  {title: "Roadsign Horse Armor", shortname: "horse.armor.roadsign"},
  {title: "Rock", shortname: "rock"},
  {title: "Rocket", shortname: "ammo.rocket.basic"},
  {title: "Rocket Launcher", shortname: "rocket.launcher"},
  {title: "Root Combiner", shortname: "electrical.combiner"},
  {title: "Rope", shortname: "rope"},
  {title: "Rotten Apple", shortname: "apple.spoiled"},
  {title: "Rowboat", shortname: "rowboat"},
  {title: "Rug", shortname: "rug"},
  {title: "Rug Bear Skin", shortname: "rug.bear"},
  {title: "Rustigé Egg - Blue", shortname: "rustige_egg_b"},
  {title: "Rustigé Egg - Green", shortname: "rustige_egg_e"},
  {title: "Rustigé Egg - Ivory", shortname: "rustige_egg_d"},
  {title: "Rustigé Egg - Purple", shortname: "rustige_egg_c"},
  {title: "Rustigé Egg - Red", shortname: "rustige_egg_a"},
  {title: "Saddle bag", shortname: "horse.saddlebag"},
  {title: "Salmon", shortname: "fish.salmon"},
  {title: "Salt Water", shortname: "water.salt"},
  {title: "Salvaged Axe", shortname: "axe.salvaged"},
  {title: "Salvaged Cleaver", shortname: "salvaged.cleaver"},
  {title: "Salvaged Hammer", shortname: "hammer.salvaged"},
  {title: "Salvaged Icepick", shortname: "icepick.salvaged"},
  {title: "Salvaged Shelves", shortname: "shelves"},
  {title: "Salvaged Sword", shortname: "salvaged.sword"},
  {title: "SAM Ammo", shortname: "ammo.rocket.sam"},
  {title: "SAM Site", shortname: "samsite"},
  {title: "Sandbag Barricade", shortname: "barricade.sandbags"},
  {title: "Santa Beard", shortname: "santabeard"},
  {title: "Santa Hat", shortname: "santahat"},
  {title: "Sardine", shortname: "fish.sardine"},
  {title: "Satchel Charge", shortname: "explosive.satchel"},
  {title: "Scarecrow", shortname: "scarecrow"},
  {title: "Scarecrow Suit", shortname: "scarecrow.suit"},
  {title: "Scarecrow Wrap", shortname: "scarecrowhead"},
  {title: "Scientist Suit", shortname: "hazmatsuit_scientist"},
  {title: "Scientist Suit", shortname: "hazmatsuit_scientist_peacekeeper"},
  {title: "Scrap", shortname: "scrap"},
  {title: "ScrapTransportHeliRepair", shortname: "scraptransportheli.repair"},
  {title: "Search Light", shortname: "searchlight"},
  {title: "Secret Lab Chair", shortname: "secretlabchair"},
  {title: "Semi Automatic Body", shortname: "semibody"},
  {title: "Semi-Automatic Pistol", shortname: "pistol.semiauto"},
  {title: "Semi-Automatic Rifle", shortname: "rifle.semiauto"},
  {title: "Sewing Kit", shortname: "sewingkit"},
  {title: "Sheet Metal", shortname: "sheetmetal"},
  {title: "Sheet Metal Door", shortname: "door.hinged.metal"},
  {title: "Sheet Metal Double Door", shortname: "door.double.hinged.metal"},
  {title: "Shirt", shortname: "shirt.collared"},
  {title: "Shop Front", shortname: "wall.frame.shopfront"},
  {title: "Short Ice Wall", shortname: "wall.ice.wall"},
  {title: "Shorts", shortname: "pants.shorts"},
  {title: "Shotgun Trap", shortname: "guntrap"},
  {title: "Shovel Bass", shortname: "fun.bass"},
  {title: "Sickle", shortname: "sickle"},
  {title: "Silencer", shortname: "weapon.mod.silencer"},
  {title: "Silver Egg", shortname: "easter.silveregg"},
  {title: "Simple Handmade Sight", shortname: "weapon.mod.simplesight"},
  {title: "Simple Light", shortname: "electric.simplelight"},
  {title: "Single Sign Post", shortname: "sign.post.single"},
  {title: "Siren Light", shortname: "electric.sirenlight"},
  {title: "Skull", shortname: "skull"},
  {title: "Skull Door Knocker", shortname: "skulldoorknocker"},
  {title: "Skull Fire Pit", shortname: "skull_fire_pit"},
  {title: "Skull Spikes", shortname: "skullspikes.candles"},
  {title: "Skull Spikes", shortname: "skullspikes.pumpkin"},
  {title: "Skull Spikes", shortname: "skullspikes"},
  {title: "Skull Trophy", shortname: "skull.trophy"},
  {title: "Skull Trophy", shortname: "skull.trophy.table"},
  {title: "Skull Trophy", shortname: "skull.trophy.jar2"},
  {title: "Skull Trophy", shortname: "skull.trophy.jar"},
  {title: "Sky Lantern", shortname: "skylantern"},
  {title: "Sky Lantern - Green", shortname: "skylantern.skylantern.green"},
  {title: "Sky Lantern - Orange", shortname: "skylantern.skylantern.orange"},
  {title: "Sky Lantern - Purple", shortname: "skylantern.skylantern.purple"},
  {title: "Sky Lantern - Red", shortname: "skylantern.skylantern.red"},
  {title: "Sled", shortname: "sled.xmas"},
  {title: "Sled", shortname: "sled"},
  {title: "Sleeping Bag", shortname: "sleepingbag"},
  {title: "Small Candle Set", shortname: "smallcandles"},
  {title: "Small Chassis", shortname: "vehicle.chassis.2mod"},
  {title: "Small Generator", shortname: "electric.fuelgenerator.small"},
  {title: "Small Loot Bag", shortname: "halloween.lootbag.small"},
  {title: "Small Neon Sign", shortname: "sign.neon.125x125"},
  {title: "Small Oil Refinery", shortname: "small.oil.refinery"},
  {title: "Small Planter Box", shortname: "planter.small"},
  {title: "Small Present", shortname: "xmas.present.small"},
  {title: "Small Rechargeable Battery", shortname: "electric.battery.rechargable.small"},
  {title: "Small Shark", shortname: "fish.smallshark"},
  {title: "Small Stash", shortname: "stash.small"},
  {title: "Small Stocking", shortname: "stocking.small"},
  {title: "Small Trout", shortname: "fish.troutsmall"},
  {title: "Small Water Bottle", shortname: "smallwaterbottle"},
  {title: "Small Water Catcher", shortname: "water.catcher.small"},
  {title: "Small Wooden Sign", shortname: "sign.wooden.small"},
  {title: "Smart Alarm", shortname: "smart.alarm"},
  {title: "Smart Switch", shortname: "smart.switch"},
  {title: "SMG Body", shortname: "smgbody"},
  {title: "Smoke Grenade", shortname: "grenade.smoke"},
  {title: "Smoke Rocket WIP!!!!", shortname: "ammo.rocket.smoke"},
  {title: "Snap Trap", shortname: "trap.bear"},
  {title: "Snow Jacket", shortname: "jacket.snow"},
  {title: "Snow Machine", shortname: "snowmachine"},
  {title: "Snowball", shortname: "snowball"},
  {title: "Snowball Gun", shortname: "snowballgun"},
  {title: "Snowman", shortname: "snowman"},
  {title: "Snowman Helmet", shortname: "attire.snowman.helmet"},
  {title: "Snowmobile", shortname: "snowmobile"},
  {title: "Sofa", shortname: "sofa"},
  {title: "Sofa - Pattern", shortname: "sofa.pattern"},
  {title: "Solo Submarine", shortname: "submarinesolo"},
  {title: "Sound Light", shortname: "soundlight"},
  {title: "Sousaphone", shortname: "fun.tuba"},
  {title: "Space Suit", shortname: "hazmatsuit.spacesuit"},
  {title: "Spas-12 Shotgun", shortname: "shotgun.spas12"},
  {title: "Speargun", shortname: "speargun"},
  {title: "Speargun Spear", shortname: "speargun.spear"},
  {title: "Spider Webs", shortname: "spiderweb"},
  {title: "Spinning wheel", shortname: "spinner.wheel"},
  {title: "Splitter", shortname: "electric.splitter"},
  {title: "Spoiled Chicken", shortname: "chicken.spoiled"},
  {title: "Spoiled Human Meat", shortname: "humanmeat.spoiled"},
  {title: "Spoiled Wolf Meat", shortname: "wolfmeat.spoiled"},
  {title: "Spooky Speaker", shortname: "spookyspeaker"},
  {title: "Spray Can", shortname: "spraycan"},
  {title: "Spray Can Decal", shortname: "spraycandecal"},
  {title: "Sprinkler", shortname: "electric.sprinkler"},
  {title: "Star Tree Topper", shortname: "xmas.decoration.star"},
  {title: "Sticks", shortname: "sticks"},
  {title: "Stone Barricade", shortname: "barricade.stone"},
  {title: "Stone Fireplace", shortname: "fireplace.stone"},
  {title: "Stone Hatchet", shortname: "stonehatchet"},
  {title: "Stone Pickaxe", shortname: "stone.pickaxe"},
  {title: "Stone Spear", shortname: "spear.stone"},
  {title: "Stones", shortname: "stones"},
  {title: "Storage Adaptor", shortname: "storageadaptor"},
  {title: "Storage Monitor", shortname: "storage.monitor"},
  {title: "Storage Vehicle Module", shortname: "vehicle.1mod.storage"},
  {title: "Strengthened Glass Window", shortname: "wall.window.glass.reinforced"},
  {title: "Strobe Light", shortname: "strobelight"},
  {title: "Sulfur", shortname: "sulfur"},
  {title: "Sulfur Ore", shortname: "sulfur.ore"},
  {title: "Sunglasses", shortname: "sunglasses02black"},
  {title: "Sunglasses", shortname: "sunglasses02camo"},
  {title: "Sunglasses", shortname: "sunglasses02red"},
  {title: "Sunglasses", shortname: "sunglasses03black"},
  {title: "Sunglasses", shortname: "sunglasses03chrome"},
  {title: "Sunglasses", shortname: "sunglasses03gold"},
  {title: "Sunglasses", shortname: "sunglasses"},
  {title: "SUPER Stocking", shortname: "stocking.large"},
  {title: "Supply Signal", shortname: "supply.signal"},
  {title: "Surface torpedo", shortname: "submarine.torpedo.rising"},
  {title: "Surgeon Scrubs", shortname: "halloween.surgeonsuit"},
  {title: "Survey Charge", shortname: "surveycharge"},
  {title: "Survival Fish Trap", shortname: "fishtrap.small"},
  {title: "Switch", shortname: "electric.switch"},
  {title: "T-Shirt", shortname: "tshirt"},
  {title: "Table", shortname: "table"},
  {title: "Tactical Gloves", shortname: "tactical.gloves"},
  {title: "Tall Picture Frame", shortname: "sign.pictureframe.tall"},
  {title: "Tank Top", shortname: "shirt.tanktop"},
  {title: "Targeting Computer", shortname: "targeting.computer"},
  {title: "Tarp", shortname: "tarp"},
  {title: "Taxi Vehicle Module", shortname: "vehicle.1mod.taxi"},
  {title: "Tech Trash", shortname: "techparts"},
  {title: "Telephone", shortname: "telephone"},
  {title: "Tesla Coil", shortname: "electric.teslacoil"},
  {title: "Test Generator", shortname: "electric.generator.small"},
  {title: "Thompson", shortname: "smg.thompson"},
  {title: "Tiger Mask", shortname: "hat.tigermask"},
  {title: "Timed Explosive Charge", shortname: "explosive.timed"},
  {title: "Timer", shortname: "electric.timer"},
  {title: "Tomaha Snowmobile", shortname: "snowmobiletomaha"},
  {title: "Tool Cupboard", shortname: "cupboard.tool"},
  {title: "Torch", shortname: "torch"},
  {title: "Torpedo", shortname: "submarine.torpedo.straight"},
  {title: "Tree Lights", shortname: "xmas.decoration.lights"},
  {title: "Triangle Ladder Hatch", shortname: "floor.triangle.ladder.hatch"},
  {title: "Tuna Can Lamp", shortname: "tunalight"},
  {title: "Twitch Rivals Trophy", shortname: "trophy"},
  {title: "Two Sided Hanging Sign", shortname: "sign.hanging"},
  {title: "Two Sided Ornate Hanging Sign", shortname: "sign.hanging.ornate"},
  {title: "Two Sided Town Sign Post", shortname: "sign.post.town.roof"},
  {title: "Vending Machine", shortname: "vending.machine"},
  {title: "Violet Boomer", shortname: "firework.boomer.violet"},
  {title: "Violet Roman Candle", shortname: "firework.romancandle.violet"},
  {title: "Violet Volcano Firework", shortname: "firework.volcano.violet"},
  {title: "Vodka Bottle", shortname: "bottle.vodka"},
  {title: "Wagon", shortname: "wagon"},
  {title: "Watch Tower", shortname: "watchtower.wood"},
  {title: "Water", shortname: "water"},
  {title: "Water Barrel", shortname: "water.barrel"},
  {title: "Water Bucket", shortname: "bucket.water"},
  {title: "Water Gun", shortname: "gun.water"},
  {title: "Water Jug", shortname: "waterjug"},
  {title: "Water Pistol", shortname: "pistol.water"},
  {title: "Water Pump", shortname: "waterpump"},
  {title: "Water Purifier", shortname: "water.purifier"},
  {title: "Waterpipe Shotgun", shortname: "shotgun.waterpipe"},
  {title: "Weapon flashlight", shortname: "weapon.mod.flashlight"},
  {title: "Weapon Lasersight", shortname: "weapon.mod.lasersight"},
  {title: "Wetsuit", shortname: "diving.wetsuit"},
  {title: "Wheelbarrow Piano", shortname: "piano"},
  {title: "White Berry", shortname: "white.berry"},
  {title: "White Berry Clone", shortname: "clone.white.berry"},
  {title: "White Berry Seed", shortname: "seed.white.berry"},
  {title: "White Volcano Firework", shortname: "firework.volcano"},
  {title: "Wind Turbine", shortname: "generator.wind.scrap"},
  {title: "Wire Tool", shortname: "wiretool"},
  {title: "Wolf Headdress", shortname: "hat.wolf"},
  {title: "Wolf Skull", shortname: "skull.wolf"},
  {title: "Wood", shortname: "wood"},
  {title: "Wood Armor Helmet", shortname: "wood.armor.helmet"},
  {title: "Wood Armor Pants", shortname: "wood.armor.pants"},
  {title: "Wood Chestplate", shortname: "wood.armor.jacket"},
  {title: "Wood Double Door", shortname: "door.double.hinged.wood"},
  {title: "Wood Shutters", shortname: "shutter.wood.a"},
  {title: "Wood Storage Box", shortname: "box.wooden"},
  {title: "Wooden Arrow", shortname: "arrow.wooden"},
  {title: "Wooden Barricade", shortname: "barricade.wood"},
  {title: "Wooden Barricade Cover", shortname: "barricade.wood.cover"},
  {title: "Wooden Cross", shortname: "woodcross"},
  {title: "Wooden Door", shortname: "door.hinged.wood"},
  {title: "Wooden Floor Spikes", shortname: "spikes.floor"},
  {title: "Wooden Horse Armor", shortname: "horse.armor.wood"},
  {title: "Wooden Ladder", shortname: "ladder.wooden.wall"},
  {title: "Wooden Spear", shortname: "spear.wooden"},
  {title: "Wooden Window Bars", shortname: "wall.window.bars.wood"},
  {title: "Workbench Level 1", shortname: "workbench1"},
  {title: "Workbench Level 2", shortname: "workbench2"},
  {title: "Workbench Level 3", shortname: "workbench3"},
  {title: "Worm", shortname: "worm"},
  {title: "Wrapped Gift", shortname: "wrappedgift"},
  {title: "Wrapping Paper", shortname: "wrappingpaper"},
  {title: "XL Picture Frame", shortname: "sign.pictureframe.xl"},
  {title: "XOR Switch", shortname: "electric.xorswitch"},
  {title: "XXL Picture Frame", shortname: "sign.pictureframe.xxl"},
  {title: "Xylobone", shortname: "xylophone"},
  {title: "Yellow Berry", shortname: "yellow.berry"},
  {title: "Yellow Berry Clone", shortname: "clone.yellow.berry"},
  {title: "Yellow Berry Seed", shortname: "seed.yellow.berry"},
  {title: "Yellow Perch", shortname: "fish.yellowperch"}
]